[build]
builder = "nixpacks"

[deploy]
startCommand = "bash scripts/migrate.sh && php -S 0.0.0.0:8080 -t public"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[envs]
DB_HOST = "{{ DB_HOST }}"
DB_PORT = "{{ DB_PORT }}"
DB_USER = "{{ DB_USER }}"
DB_PASS = "{{ DB_PASS }}"
